#!/system/bin/sh
# Copyright 2014-2017 Tuxafgmur - Dhollmen

rm -f  /data/local/tmp/*
rm -f  /data/tombstones/*
rm -f  /data/system/dropbox/*
rm -f  /data/system/heapdump/*
rm -f  /data/system/procstats/*
rm -f  /data/system/uiderrors.txt

cd /data/dalvik-cache/arm
if [ "$?" != "0" ]; then
    for q in *; do
        a=$(echo $q|cut -d'@' -f1)
        b=$(echo $q|cut -d'@' -f2)
        c=$(echo $q|cut -d'@' -f3)
        case $c in
            boot.art)
            ;;
            boot.oat)
            ;;
            *)  FILE="/$a/$b/$c"
                [ -d $FILE ] || rm $q
            ;;
        esac
    done
fi
